use crate::chk;
use crate::runner::common::*;

pub async fn test_eks(endpoint: &str, verbose: bool) -> Vec<OpResult> {
    let config = make_config(endpoint).await;
    let client = aws_sdk_eks::Client::new(&config);
    let mut results = Vec::new();

    results.push(chk!(
        "CreateCluster",
        client
            .create_cluster()
            .name("conf-cluster")
            .role_arn("arn:aws:iam::000000000000:role/conf")
            .resources_vpc_config(
                aws_sdk_eks::types::VpcConfigRequest::builder()
                    .subnet_ids("subnet-123")
                    .build(),
            )
            .send()
            .await,
        verbose
    ));
    results.push(chk!(
        "DescribeCluster",
        client.describe_cluster().name("conf-cluster").send().await,
        verbose
    ));
    results.push(chk!(
        "ListClusters",
        client.list_clusters().send().await,
        verbose
    ));
    results.push(chk!(
        "CreateNodegroup",
        client
            .create_nodegroup()
            .cluster_name("conf-cluster")
            .nodegroup_name("conf-ng")
            .node_role("arn:aws:iam::000000000000:role/ng")
            .subnets("subnet-123")
            .send()
            .await,
        verbose
    ));
    results.push(chk!(
        "DescribeNodegroup",
        client
            .describe_nodegroup()
            .cluster_name("conf-cluster")
            .nodegroup_name("conf-ng")
            .send()
            .await,
        verbose
    ));
    results.push(chk!(
        "ListNodegroups",
        client
            .list_nodegroups()
            .cluster_name("conf-cluster")
            .send()
            .await,
        verbose
    ));
    results.push(chk!(
        "CreateFargateProfile",
        client
            .create_fargate_profile()
            .cluster_name("conf-cluster")
            .fargate_profile_name("conf-fp")
            .pod_execution_role_arn("arn:aws:iam::000000000000:role/fp")
            .send()
            .await,
        verbose
    ));
    results.push(chk!(
        "DescribeFargateProfile",
        client
            .describe_fargate_profile()
            .cluster_name("conf-cluster")
            .fargate_profile_name("conf-fp")
            .send()
            .await,
        verbose
    ));
    results.push(chk!(
        "ListFargateProfiles",
        client
            .list_fargate_profiles()
            .cluster_name("conf-cluster")
            .send()
            .await,
        verbose
    ));
    results.push(chk!(
        "TagResource",
        client
            .tag_resource()
            .resource_arn("arn:aws:eks:us-east-1:000000000000:cluster/conf-cluster")
            .tags("env", "conformance")
            .send()
            .await,
        verbose
    ));
    results.push(chk!(
        "ListTagsForResource",
        client
            .list_tags_for_resource()
            .resource_arn("arn:aws:eks:us-east-1:000000000000:cluster/conf-cluster")
            .send()
            .await,
        verbose
    ));
    results.push(chk!(
        "DeleteFargateProfile",
        client
            .delete_fargate_profile()
            .cluster_name("conf-cluster")
            .fargate_profile_name("conf-fp")
            .send()
            .await,
        verbose
    ));
    results.push(chk!(
        "DeleteNodegroup",
        client
            .delete_nodegroup()
            .cluster_name("conf-cluster")
            .nodegroup_name("conf-ng")
            .send()
            .await,
        verbose
    ));
    results.push(chk!(
        "DeleteCluster",
        client.delete_cluster().name("conf-cluster").send().await,
        verbose
    ));

    results
}
