use crate::chk;
use crate::runner::common::*;

pub async fn test_firehose(endpoint: &str, verbose: bool) -> Vec<OpResult> {
    let config = make_config(endpoint).await;
    let client = aws_sdk_firehose::Client::new(&config);
    let mut results = Vec::new();

    results.push(chk!(
        "CreateDeliveryStream",
        client
            .create_delivery_stream()
            .delivery_stream_name("conf-stream")
            .delivery_stream_type(aws_sdk_firehose::types::DeliveryStreamType::DirectPut)
            .send()
            .await,
        verbose
    ));
    results.push(chk!(
        "DescribeDeliveryStream",
        client
            .describe_delivery_stream()
            .delivery_stream_name("conf-stream")
            .send()
            .await,
        verbose
    ));
    results.push(chk!(
        "ListDeliveryStreams",
        client.list_delivery_streams().send().await,
        verbose
    ));
    results.push(chk!(
        "PutRecord",
        client
            .put_record()
            .delivery_stream_name("conf-stream")
            .record(
                aws_sdk_firehose::types::Record::builder()
                    .data(aws_sdk_firehose::primitives::Blob::new(b"hello".to_vec()))
                    .build()
                    .unwrap(),
            )
            .send()
            .await,
        verbose
    ));
    results.push(chk!(
        "PutRecordBatch",
        client
            .put_record_batch()
            .delivery_stream_name("conf-stream")
            .records(
                aws_sdk_firehose::types::Record::builder()
                    .data(aws_sdk_firehose::primitives::Blob::new(b"a".to_vec()))
                    .build()
                    .unwrap(),
            )
            .send()
            .await,
        verbose
    ));
    results.push(chk!(
        "TagDeliveryStream",
        client
            .tag_delivery_stream()
            .delivery_stream_name("conf-stream")
            .tags(
                aws_sdk_firehose::types::Tag::builder()
                    .key("env")
                    .value("conf")
                    .build()
                    .unwrap(),
            )
            .send()
            .await,
        verbose
    ));
    results.push(chk!(
        "ListTagsForDeliveryStream",
        client
            .list_tags_for_delivery_stream()
            .delivery_stream_name("conf-stream")
            .send()
            .await,
        verbose
    ));
    results.push(chk!(
        "UntagDeliveryStream",
        client
            .untag_delivery_stream()
            .delivery_stream_name("conf-stream")
            .tag_keys("env")
            .send()
            .await,
        verbose
    ));
    results.push(chk!(
        "StartDeliveryStreamEncryption",
        client
            .start_delivery_stream_encryption()
            .delivery_stream_name("conf-stream")
            .send()
            .await,
        verbose
    ));
    results.push(chk!(
        "StopDeliveryStreamEncryption",
        client
            .stop_delivery_stream_encryption()
            .delivery_stream_name("conf-stream")
            .send()
            .await,
        verbose
    ));
    results.push(chk!(
        "DeleteDeliveryStream",
        client
            .delete_delivery_stream()
            .delivery_stream_name("conf-stream")
            .send()
            .await,
        verbose
    ));

    results
}
