//! Route53 GeoLocation catalog.
//!
//! AWS Route53 supports geolocation routing keyed by ISO 3166-1
//! alpha-2 country codes, continent codes, and (for the US only) ISO
//! 3166-2 subdivision codes. `ListGeoLocations` returns every entry
//! AWS recognizes; this module is the data table behind that.
//!
//! Names are kept ASCII-only: a few official names contain non-ASCII
//! characters (e.g. Cote d'Ivoire, Aland Islands) which are
//! transliterated here.

/// Continent rows: `(code, name)`.
pub const CONTINENTS: &[(&str, &str)] = &[
    ("AF", "Africa"),
    ("AN", "Antarctica"),
    ("AS", "Asia"),
    ("EU", "Europe"),
    ("NA", "North America"),
    ("OC", "Oceania"),
    ("SA", "South America"),
];

/// Country rows: `(continent_code, country_code, country_name)`.
/// ISO 3166-1 alpha-2 codes; ASCII names only.
pub const COUNTRIES: &[(&str, &str, &str)] = &[
    // Africa
    ("AF", "DZ", "Algeria"),
    ("AF", "AO", "Angola"),
    ("AF", "BJ", "Benin"),
    ("AF", "BW", "Botswana"),
    ("AF", "BF", "Burkina Faso"),
    ("AF", "BI", "Burundi"),
    ("AF", "CV", "Cabo Verde"),
    ("AF", "CM", "Cameroon"),
    ("AF", "CF", "Central African Republic"),
    ("AF", "TD", "Chad"),
    ("AF", "KM", "Comoros"),
    ("AF", "CG", "Congo"),
    ("AF", "CD", "Congo (Democratic Republic)"),
    ("AF", "CI", "Cote d'Ivoire"),
    ("AF", "DJ", "Djibouti"),
    ("AF", "EG", "Egypt"),
    ("AF", "GQ", "Equatorial Guinea"),
    ("AF", "ER", "Eritrea"),
    ("AF", "SZ", "Eswatini"),
    ("AF", "ET", "Ethiopia"),
    ("AF", "GA", "Gabon"),
    ("AF", "GM", "Gambia"),
    ("AF", "GH", "Ghana"),
    ("AF", "GN", "Guinea"),
    ("AF", "GW", "Guinea-Bissau"),
    ("AF", "KE", "Kenya"),
    ("AF", "LS", "Lesotho"),
    ("AF", "LR", "Liberia"),
    ("AF", "LY", "Libya"),
    ("AF", "MG", "Madagascar"),
    ("AF", "MW", "Malawi"),
    ("AF", "ML", "Mali"),
    ("AF", "MR", "Mauritania"),
    ("AF", "MU", "Mauritius"),
    ("AF", "YT", "Mayotte"),
    ("AF", "MA", "Morocco"),
    ("AF", "MZ", "Mozambique"),
    ("AF", "NA", "Namibia"),
    ("AF", "NE", "Niger"),
    ("AF", "NG", "Nigeria"),
    ("AF", "RE", "Reunion"),
    ("AF", "RW", "Rwanda"),
    ("AF", "SH", "Saint Helena"),
    ("AF", "ST", "Sao Tome and Principe"),
    ("AF", "SN", "Senegal"),
    ("AF", "SC", "Seychelles"),
    ("AF", "SL", "Sierra Leone"),
    ("AF", "SO", "Somalia"),
    ("AF", "ZA", "South Africa"),
    ("AF", "SS", "South Sudan"),
    ("AF", "SD", "Sudan"),
    ("AF", "TZ", "Tanzania"),
    ("AF", "TG", "Togo"),
    ("AF", "TN", "Tunisia"),
    ("AF", "UG", "Uganda"),
    ("AF", "EH", "Western Sahara"),
    ("AF", "ZM", "Zambia"),
    ("AF", "ZW", "Zimbabwe"),
    // Antarctica
    ("AN", "AQ", "Antarctica"),
    ("AN", "BV", "Bouvet Island"),
    ("AN", "TF", "French Southern Territories"),
    ("AN", "HM", "Heard Island and McDonald Islands"),
    ("AN", "GS", "South Georgia and the South Sandwich Islands"),
    // Asia
    ("AS", "AF", "Afghanistan"),
    ("AS", "AM", "Armenia"),
    ("AS", "AZ", "Azerbaijan"),
    ("AS", "BH", "Bahrain"),
    ("AS", "BD", "Bangladesh"),
    ("AS", "BT", "Bhutan"),
    ("AS", "BN", "Brunei Darussalam"),
    ("AS", "KH", "Cambodia"),
    ("AS", "CN", "China"),
    ("AS", "CY", "Cyprus"),
    ("AS", "GE", "Georgia"),
    ("AS", "HK", "Hong Kong"),
    ("AS", "IN", "India"),
    ("AS", "ID", "Indonesia"),
    ("AS", "IR", "Iran"),
    ("AS", "IQ", "Iraq"),
    ("AS", "IL", "Israel"),
    ("AS", "JP", "Japan"),
    ("AS", "JO", "Jordan"),
    ("AS", "KZ", "Kazakhstan"),
    ("AS", "KP", "Korea (North)"),
    ("AS", "KR", "Korea (South)"),
    ("AS", "KW", "Kuwait"),
    ("AS", "KG", "Kyrgyzstan"),
    ("AS", "LA", "Laos"),
    ("AS", "LB", "Lebanon"),
    ("AS", "MO", "Macao"),
    ("AS", "MY", "Malaysia"),
    ("AS", "MV", "Maldives"),
    ("AS", "MN", "Mongolia"),
    ("AS", "MM", "Myanmar"),
    ("AS", "NP", "Nepal"),
    ("AS", "OM", "Oman"),
    ("AS", "PK", "Pakistan"),
    ("AS", "PS", "Palestine"),
    ("AS", "PH", "Philippines"),
    ("AS", "QA", "Qatar"),
    ("AS", "SA", "Saudi Arabia"),
    ("AS", "SG", "Singapore"),
    ("AS", "LK", "Sri Lanka"),
    ("AS", "SY", "Syria"),
    ("AS", "TW", "Taiwan"),
    ("AS", "TJ", "Tajikistan"),
    ("AS", "TH", "Thailand"),
    ("AS", "TL", "Timor-Leste"),
    ("AS", "TR", "Turkey"),
    ("AS", "TM", "Turkmenistan"),
    ("AS", "AE", "United Arab Emirates"),
    ("AS", "UZ", "Uzbekistan"),
    ("AS", "VN", "Viet Nam"),
    ("AS", "YE", "Yemen"),
    // Europe
    ("EU", "AX", "Aland Islands"),
    ("EU", "AL", "Albania"),
    ("EU", "AD", "Andorra"),
    ("EU", "AT", "Austria"),
    ("EU", "BY", "Belarus"),
    ("EU", "BE", "Belgium"),
    ("EU", "BA", "Bosnia and Herzegovina"),
    ("EU", "BG", "Bulgaria"),
    ("EU", "HR", "Croatia"),
    ("EU", "CZ", "Czechia"),
    ("EU", "DK", "Denmark"),
    ("EU", "EE", "Estonia"),
    ("EU", "FO", "Faroe Islands"),
    ("EU", "FI", "Finland"),
    ("EU", "FR", "France"),
    ("EU", "DE", "Germany"),
    ("EU", "GI", "Gibraltar"),
    ("EU", "GR", "Greece"),
    ("EU", "GG", "Guernsey"),
    ("EU", "VA", "Holy See"),
    ("EU", "HU", "Hungary"),
    ("EU", "IS", "Iceland"),
    ("EU", "IE", "Ireland"),
    ("EU", "IM", "Isle of Man"),
    ("EU", "IT", "Italy"),
    ("EU", "JE", "Jersey"),
    ("EU", "LV", "Latvia"),
    ("EU", "LI", "Liechtenstein"),
    ("EU", "LT", "Lithuania"),
    ("EU", "LU", "Luxembourg"),
    ("EU", "MT", "Malta"),
    ("EU", "MD", "Moldova"),
    ("EU", "MC", "Monaco"),
    ("EU", "ME", "Montenegro"),
    ("EU", "NL", "Netherlands"),
    ("EU", "MK", "North Macedonia"),
    ("EU", "NO", "Norway"),
    ("EU", "PL", "Poland"),
    ("EU", "PT", "Portugal"),
    ("EU", "RO", "Romania"),
    ("EU", "RU", "Russian Federation"),
    ("EU", "SM", "San Marino"),
    ("EU", "RS", "Serbia"),
    ("EU", "SK", "Slovakia"),
    ("EU", "SI", "Slovenia"),
    ("EU", "ES", "Spain"),
    ("EU", "SJ", "Svalbard and Jan Mayen"),
    ("EU", "SE", "Sweden"),
    ("EU", "CH", "Switzerland"),
    ("EU", "UA", "Ukraine"),
    ("EU", "GB", "United Kingdom"),
    // North America
    ("NA", "AI", "Anguilla"),
    ("NA", "AG", "Antigua and Barbuda"),
    ("NA", "AW", "Aruba"),
    ("NA", "BS", "Bahamas"),
    ("NA", "BB", "Barbados"),
    ("NA", "BZ", "Belize"),
    ("NA", "BM", "Bermuda"),
    ("NA", "BQ", "Bonaire, Sint Eustatius and Saba"),
    ("NA", "CA", "Canada"),
    ("NA", "KY", "Cayman Islands"),
    ("NA", "CR", "Costa Rica"),
    ("NA", "CU", "Cuba"),
    ("NA", "CW", "Curacao"),
    ("NA", "DM", "Dominica"),
    ("NA", "DO", "Dominican Republic"),
    ("NA", "SV", "El Salvador"),
    ("NA", "GL", "Greenland"),
    ("NA", "GD", "Grenada"),
    ("NA", "GP", "Guadeloupe"),
    ("NA", "GT", "Guatemala"),
    ("NA", "HT", "Haiti"),
    ("NA", "HN", "Honduras"),
    ("NA", "JM", "Jamaica"),
    ("NA", "MQ", "Martinique"),
    ("NA", "MX", "Mexico"),
    ("NA", "MS", "Montserrat"),
    ("NA", "NI", "Nicaragua"),
    ("NA", "PA", "Panama"),
    ("NA", "PR", "Puerto Rico"),
    ("NA", "BL", "Saint Barthelemy"),
    ("NA", "KN", "Saint Kitts and Nevis"),
    ("NA", "LC", "Saint Lucia"),
    ("NA", "MF", "Saint Martin"),
    ("NA", "PM", "Saint Pierre and Miquelon"),
    ("NA", "VC", "Saint Vincent and the Grenadines"),
    ("NA", "SX", "Sint Maarten"),
    ("NA", "TT", "Trinidad and Tobago"),
    ("NA", "TC", "Turks and Caicos Islands"),
    ("NA", "US", "United States"),
    ("NA", "VG", "Virgin Islands (British)"),
    ("NA", "VI", "Virgin Islands (U.S.)"),
    // Oceania
    ("OC", "AS", "American Samoa"),
    ("OC", "AU", "Australia"),
    ("OC", "CX", "Christmas Island"),
    ("OC", "CC", "Cocos (Keeling) Islands"),
    ("OC", "CK", "Cook Islands"),
    ("OC", "FJ", "Fiji"),
    ("OC", "PF", "French Polynesia"),
    ("OC", "GU", "Guam"),
    ("OC", "KI", "Kiribati"),
    ("OC", "MH", "Marshall Islands"),
    ("OC", "FM", "Micronesia"),
    ("OC", "NR", "Nauru"),
    ("OC", "NC", "New Caledonia"),
    ("OC", "NZ", "New Zealand"),
    ("OC", "NU", "Niue"),
    ("OC", "NF", "Norfolk Island"),
    ("OC", "MP", "Northern Mariana Islands"),
    ("OC", "PW", "Palau"),
    ("OC", "PG", "Papua New Guinea"),
    ("OC", "PN", "Pitcairn"),
    ("OC", "WS", "Samoa"),
    ("OC", "SB", "Solomon Islands"),
    ("OC", "TK", "Tokelau"),
    ("OC", "TO", "Tonga"),
    ("OC", "TV", "Tuvalu"),
    ("OC", "UM", "United States Minor Outlying Islands"),
    ("OC", "VU", "Vanuatu"),
    ("OC", "WF", "Wallis and Futuna"),
    // South America
    ("SA", "AR", "Argentina"),
    ("SA", "BO", "Bolivia"),
    ("SA", "BR", "Brazil"),
    ("SA", "CL", "Chile"),
    ("SA", "CO", "Colombia"),
    ("SA", "EC", "Ecuador"),
    ("SA", "FK", "Falkland Islands"),
    ("SA", "GF", "French Guiana"),
    ("SA", "GY", "Guyana"),
    ("SA", "PY", "Paraguay"),
    ("SA", "PE", "Peru"),
    ("SA", "SR", "Suriname"),
    ("SA", "UY", "Uruguay"),
    ("SA", "VE", "Venezuela"),
];

/// US ISO 3166-2 subdivision rows: `(subdivision_code, name)`. AWS
/// only exposes subdivisions for the US.
pub const US_SUBDIVISIONS: &[(&str, &str)] = &[
    ("AL", "Alabama"),
    ("AK", "Alaska"),
    ("AZ", "Arizona"),
    ("AR", "Arkansas"),
    ("CA", "California"),
    ("CO", "Colorado"),
    ("CT", "Connecticut"),
    ("DE", "Delaware"),
    ("DC", "District of Columbia"),
    ("FL", "Florida"),
    ("GA", "Georgia"),
    ("HI", "Hawaii"),
    ("ID", "Idaho"),
    ("IL", "Illinois"),
    ("IN", "Indiana"),
    ("IA", "Iowa"),
    ("KS", "Kansas"),
    ("KY", "Kentucky"),
    ("LA", "Louisiana"),
    ("ME", "Maine"),
    ("MD", "Maryland"),
    ("MA", "Massachusetts"),
    ("MI", "Michigan"),
    ("MN", "Minnesota"),
    ("MS", "Mississippi"),
    ("MO", "Missouri"),
    ("MT", "Montana"),
    ("NE", "Nebraska"),
    ("NV", "Nevada"),
    ("NH", "New Hampshire"),
    ("NJ", "New Jersey"),
    ("NM", "New Mexico"),
    ("NY", "New York"),
    ("NC", "North Carolina"),
    ("ND", "North Dakota"),
    ("OH", "Ohio"),
    ("OK", "Oklahoma"),
    ("OR", "Oregon"),
    ("PA", "Pennsylvania"),
    ("RI", "Rhode Island"),
    ("SC", "South Carolina"),
    ("SD", "South Dakota"),
    ("TN", "Tennessee"),
    ("TX", "Texas"),
    ("UT", "Utah"),
    ("VT", "Vermont"),
    ("VA", "Virginia"),
    ("WA", "Washington"),
    ("WV", "West Virginia"),
    ("WI", "Wisconsin"),
    ("WY", "Wyoming"),
];

/// Look up a continent by code, returning its name.
pub fn continent_name(code: &str) -> Option<&'static str> {
    CONTINENTS.iter().find(|(c, _)| *c == code).map(|(_, n)| *n)
}

/// Look up a country by code, returning `(continent_code, name)`.
pub fn country_info(code: &str) -> Option<(&'static str, &'static str)> {
    COUNTRIES
        .iter()
        .find(|(_, c, _)| *c == code)
        .map(|(cont, _, name)| (*cont, *name))
}

/// Look up a US subdivision by code, returning its name.
pub fn us_subdivision_name(code: &str) -> Option<&'static str> {
    US_SUBDIVISIONS
        .iter()
        .find(|(c, _)| *c == code)
        .map(|(_, n)| *n)
}
